/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mamehub.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ChatStatus implements org.apache.thrift.TEnum {
  ONLINE(0),
  QUIET(1),
  AWAY(2);

  private final int value;

  private ChatStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ChatStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return ONLINE;
      case 1:
        return QUIET;
      case 2:
        return AWAY;
      default:
        return null;
    }
  }
}
