/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mamehub.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MR implements org.apache.thrift.TEnum {
  MISSING_FILES(0),
  BAD_FILES(1),
  MISSING_CLONE(2),
  MISSING_PARENT(3);

  private final int value;

  private MR(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MR findByValue(int value) { 
    switch (value) {
      case 0:
        return MISSING_FILES;
      case 1:
        return BAD_FILES;
      case 2:
        return MISSING_CLONE;
      case 3:
        return MISSING_PARENT;
      default:
        return null;
    }
  }
}
